"""Attempt git rebase onto target branch, report conflict files."""

import os
import subprocess
from typing import Optional


def attempt_rebase(
    source_branch: str,
    target_branch: str = "main",
    dry_run: bool = True,
    work_dir: Optional[str] = None,
) -> dict:
    """Attempt (or dry-run) a rebase of source_branch onto target_branch.

    Uses ``git merge-tree`` to detect conflicts without modifying the
    working tree when ``dry_run=True`` (default).

    Args:
        source_branch: Branch to rebase.
        target_branch: Base branch (default: main).
        dry_run: If True, only check for conflicts without rebasing.
        work_dir: Optional git working directory. Defaults to CWD.

    Returns:
        dict with keys:
          - success (bool)
          - conflict_files (list[str]) — files with conflicts
          - error (str or None)
    """
    if work_dir is None:
        work_dir = os.getcwd()

    # Fetch latest from origin first
    subprocess.run(
        ["git", "fetch", "origin", target_branch],
        capture_output=True,
        text=True,
        cwd=work_dir,
    )

    # Conflict detection via merge-tree
    try:
        base_sha = subprocess.run(
            ["git", "merge-base", "HEAD", f"origin/{target_branch}"],
            capture_output=True,
            text=True,
            check=True,
            cwd=work_dir,
        ).stdout.strip()
    except subprocess.CalledProcessError:
        return {"success": False, "conflict_files": [], "error": "merge-base not found"}

    merge_tree = subprocess.run(
        ["git", "merge-tree", base_sha, "HEAD", f"origin/{target_branch}"],
        capture_output=True,
        text=True,
        cwd=work_dir,
    )
    output = merge_tree.stdout

    conflict_files = _parse_merge_tree_conflicts(output)

    if dry_run:
        return {
            "success": not conflict_files,
            "conflict_files": conflict_files,
            "error": "conflicts detected" if conflict_files else None,
        }

    # Live rebase (destructive — use with caution)
    if conflict_files:
        return {
            "success": False,
            "conflict_files": conflict_files,
            "error": "cannot rebase with unresolved conflicts",
        }

    try:
        rebase_result = subprocess.run(
            ["git", "rebase", f"origin/{target_branch}"],
            capture_output=True,
            text=True,
            cwd=work_dir,
        )
        if rebase_result.returncode == 0:
            return {"success": True, "conflict_files": [], "error": None}
        subprocess.run(
            ["git", "rebase", "--abort"],
            capture_output=True,
            text=True,
            cwd=work_dir,
        )
        return {
            "success": False,
            "conflict_files": [],
            "error": rebase_result.stderr[:500] if rebase_result.stderr else "rebase failed",
        }
    except subprocess.CalledProcessError as exc:
        subprocess.run(
            ["git", "rebase", "--abort"],
            capture_output=True,
            text=True,
            cwd=work_dir,
        )
        return {"success": False, "conflict_files": [], "error": str(exc)}


def _parse_merge_tree_conflicts(merge_tree_output: str) -> list[str]:
    """Parse conflict file paths from ``git merge-tree`` output."""
    conflict_files: list[str] = []
    for line in merge_tree_output.splitlines():
        if line.startswith("CONFLICT (content):"):
            # e.g. "CONFLICT (content): Merge conflict in src/file.py"
            parts = line.split(" in ")
            if len(parts) > 1:
                conflict_files.append(parts[1].strip().rstrip("."))
        elif "changed in both" in line.lower():
            # Fallback for alternative conflict formats
            tokens = line.split()
            if tokens:
                conflict_files.append(tokens[-1].strip())
    return conflict_files


def save_conflict_patch(
    pr_number: int, conflict_files: list[str], output_path: str
) -> str:
    """Save a conflict-annotated diff patch for a failed rebase."""
    result = subprocess.run(
        ["git", "diff"],
        capture_output=True,
        text=True,
    )
    header = (
        f"# PR #{pr_number} — Conflict Patch\n"
        f"# Generated by triage framework\n"
        f"# Conflicting files: {', '.join(conflict_files)}\n"
        f"{'=' * 60}\n"
    )
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)
        f.write(result.stdout)
    return output_path
