#!/usr/bin/env bash
set -euo pipefail

stage="${1:?stage is required}"

repo_root="$(pwd)"
handoff=".agent/handoff/${stage}.md"
state_path=".agent/state.json"

if [[ ! -f "$handoff" ]]; then
  echo "Missing handoff: $handoff" >&2
  exit 2
fi

if [[ ! -f "$state_path" ]]; then
  echo "Missing pipeline state: $state_path" >&2
  exit 2
fi

feature_id="$(
  python3 - <<'PY'
import json
from pathlib import Path

state = json.loads(Path(".agent/state.json").read_text(encoding="utf-8"))
print(state.get("feature_id", "unknown-feature"))
PY
)"

today="$(date +%Y-%m-%d)"

case "$stage" in
  claude_lead_plan)
    out_dir="docs/dev_plans"
    out_path="${out_dir}/${today}-${feature_id}-team-plan.md"
    mkdir -p "$out_dir"
    {
      printf '# %s Team Plan\n\n' "$feature_id"
      printf '> Smoke-test team plan generated by local Claude wrapper.\n'
      printf '> This proves GitHub Actions can call WSL and execute the Claude lead stage command.\n\n'
      printf '## Stage\n\n'
      printf 'claude_lead_plan\n\n'
      printf '## Source Handoff\n\n'
      printf '%s\n\n' "$handoff"
      printf '## Phase Plan\n\n'
      printf '| Phase | Owner | Goal | Expected Evidence |\n'
      printf '|---|---|---|---|\n'
      printf '| phase-1 | Claude Code B | Verify phase development handoff can run | `docs/dev_reports/%s-phase-1-dev-report.md` |\n' "$feature_id"
      printf '| phase-1-test | Claude Code C | Verify phase testing handoff can run | `docs/test_reports/%s-phase-1-test-report.md` |\n\n' "$feature_id"
      printf '## Routing Rule\n\n'
      printf 'After Claude Code C passes a phase, route back to Claude Code B unless all phases are tested. Only then route to Claude Code A lead review.\n\n'
      printf '## Safety Notes\n\n'
      printf '%s\n' '- This smoke test must not modify trading, risk, execution, broker, account, or live-trading modules.'
      printf '%s\n\n' '- This smoke test does not call a real model. Replace this wrapper body with ccswitch/opencode-go/DeepSeek after the command chain is verified.'
      printf '## Handoff Preview\n\n'
      printf '```text\n'
      head -c 1200 "$handoff" || true
      printf '\n```\n'
    } > "$out_path"
    echo "Generated $out_path"
    ;;
  *)
    echo "Unsupported smoke-test Claude stage: $stage" >&2
    exit 2
    ;;
esac

echo "Claude stage smoke complete in $repo_root"
