#!/usr/bin/env bash
set -euo pipefail

stage="${1:?stage is required}"

repo_root="$(pwd)"
handoff=".agent/handoff/${stage}.md"
state_path=".agent/state.json"

if [[ ! -f "$handoff" ]]; then
  echo "Missing handoff: $handoff" >&2
  exit 2
fi

if [[ ! -f "$state_path" ]]; then
  echo "Missing pipeline state: $state_path" >&2
  exit 2
fi

feature_id="$(
  python3 - <<'PY'
import json
from pathlib import Path

state = json.loads(Path(".agent/state.json").read_text(encoding="utf-8"))
print(state.get("feature_id", "unknown-feature"))
PY
)"

today="$(date +%Y-%m-%d)"

case "$stage" in
  claude_lead_plan)
    out_dir="docs/dev_plans"
    out_path="${out_dir}/${today}-${feature_id}-team-plan.md"
    mkdir -p "$out_dir"
    {
      printf '# %s Team Plan\n\n' "$feature_id"
      printf '> Smoke-test team plan generated by local Claude wrapper.\n'
      printf '> This proves GitHub Actions can call WSL and execute the Claude lead stage command.\n\n'
      printf '## Stage\n\n'
      printf 'claude_lead_plan\n\n'
      printf '## Source Handoff\n\n'
      printf '%s\n\n' "$handoff"
      printf '## Phase Plan\n\n'
      printf '| Phase | Owner | Goal | Expected Evidence |\n'
      printf '|---|---|---|---|\n'
      printf '| phase-1 | Claude Code B | Verify phase development handoff can run | `docs/dev_reports/%s-phase-1-dev-report.md` |\n' "$feature_id"
      printf '| phase-1-test | Claude Code C | Verify phase testing handoff can run | `docs/test_reports/%s-phase-1-test-report.md` |\n\n' "$feature_id"
      printf '## Routing Rule\n\n'
      printf 'After Claude Code C passes a phase, route back to Claude Code B unless all phases are tested. Only then route to Claude Code A lead review.\n\n'
      printf '## Safety Notes\n\n'
      printf '%s\n' '- This smoke test must not modify trading, risk, execution, broker, account, or live-trading modules.'
      printf '%s\n\n' '- This smoke test does not call a real model. Replace this wrapper body with ccswitch/opencode-go/DeepSeek after the command chain is verified.'
      printf '## Handoff Preview\n\n'
      printf '```text\n'
      head -c 1200 "$handoff" || true
      printf '\n```\n'
    } > "$out_path"
    echo "Generated $out_path"
    ;;
  claude_developer)
    out_dir="docs/dev_reports"
    out_path="${out_dir}/${today}-${feature_id}-phase-1-dev-report.md"
    mkdir -p "$out_dir"
    {
      printf '# %s Phase 1 Development Report\n\n' "$feature_id"
      printf '> Smoke-test development report generated by local Claude wrapper.\n'
      printf '> This proves GitHub Actions can call the Claude Code B phase developer stage command.\n\n'
      printf '## Stage\n\n'
      printf 'claude_developer\n\n'
      printf '## Source Handoff\n\n'
      printf '%s\n\n' "$handoff"
      printf '## Implemented Scope\n\n'
      printf '%s\n' '- Verified the Claude developer stage command can execute in WSL.'
      printf '%s\n' '- Did not modify product trading logic.'
      printf '%s\n\n' '- Did not call a real model during this smoke test.'
      printf '## Self-Test Commands\n\n'
      printf '```bash\n'
      printf 'bash scripts/run_claude_stage.sh claude_developer\n'
      printf '```\n\n'
      printf '## Result\n\n'
      printf 'PASS\n\n'
      printf '## Handoff Preview\n\n'
      printf '```text\n'
      head -c 1200 "$handoff" || true
      printf '\n```\n'
    } > "$out_path"
    echo "Generated $out_path"
    ;;
  claude_tester)
    out_dir="docs/test_reports"
    out_path="${out_dir}/${today}-${feature_id}-phase-1-test-report.md"
    mkdir -p "$out_dir"
    {
      printf '# %s Phase 1 Test Report\n\n' "$feature_id"
      printf '> Smoke-test test report generated by local Claude wrapper.\n'
      printf '> This proves GitHub Actions can call the Claude Code C phase tester stage command.\n\n'
      printf '## Stage\n\n'
      printf 'claude_tester\n\n'
      printf '## Source Handoff\n\n'
      printf '%s\n\n' "$handoff"
      printf '## Test Matrix\n\n'
      printf '| Check | Result |\n'
      printf '|---|---|\n'
      printf '| Handoff file exists | PASS |\n'
      printf '| Pipeline state exists | PASS |\n'
      printf '| Phase dev report expected path | PASS |\n'
      printf '| No production trading logic modified | PASS |\n\n'
      printf '## Final Result\n\n'
      printf 'PASS\n\n'
      printf '## Handoff Preview\n\n'
      printf '```text\n'
      head -c 1200 "$handoff" || true
      printf '\n```\n'
    } > "$out_path"

    python3 - <<'PY'
import json
from pathlib import Path

path = Path(".agent/state.json")
state = json.loads(path.read_text(encoding="utf-8"))
team = state.setdefault("team_pipeline", {})
team["current_phase"] = 1
team["all_phases_tested"] = True
path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
PY

    python3 - <<'PY'
from pathlib import Path
import yaml

state_path = Path(".agent/state.json")
task_path = Path(".agent/current_task.yaml")
if state_path.exists() and task_path.exists():
    import json
    state = json.loads(state_path.read_text(encoding="utf-8"))
    task_path.write_text(yaml.safe_dump(state, allow_unicode=True, sort_keys=False), encoding="utf-8")
PY

    echo "Generated $out_path"
    echo "Updated .agent/state.json team_pipeline.all_phases_tested=true"
    ;;
  claude_lead_review)
    out_dir="docs/review"
    out_path="${out_dir}/${today}-${feature_id}-claude-lead-review.md"
    mkdir -p "$out_dir"
    {
      printf '# %s Claude Lead Review\n\n' "$feature_id"
      printf '> Smoke-test lead review generated by local Claude wrapper.\n'
      printf '> This proves GitHub Actions can call the Claude Code A lead review stage command.\n\n'
      printf '## Stage\n\n'
      printf 'claude_lead_review\n\n'
      printf '## Source Handoff\n\n'
      printf '%s\n\n' "$handoff"
      printf '## Reviewed Evidence\n\n'
      printf '| Evidence | Expected Pattern | Result |\n'
      printf '|---|---|---|\n'
      printf '| Team plan | `docs/dev_plans/*-%s-team-plan.md` | PASS |\n' "$feature_id"
      printf '| Phase dev report | `docs/dev_reports/*-%s-phase-1-dev-report.md` | PASS |\n' "$feature_id"
      printf '| Phase test report | `docs/test_reports/*-%s-phase-1-test-report.md` | PASS |\n\n' "$feature_id"
      printf '## Lead Review Result\n\n'
      printf 'APPROVED\n\n'
      printf '## Handoff to Codex B\n\n'
      printf 'All smoke-test phases are complete. Route to `stage:codex-review-pending` for Codex B final review.\n\n'
      printf '## Safety Notes\n\n'
      printf '%s\n' '- This smoke test did not modify trading, risk, execution, broker, account, or live-trading modules.'
      printf '%s\n\n' '- This smoke test does not replace real code review for production features.'
      printf '## Handoff Preview\n\n'
      printf '```text\n'
      head -c 1200 "$handoff" || true
      printf '\n```\n'
    } > "$out_path"
    echo "Generated $out_path"
    ;;
  *)
    echo "Unsupported smoke-test Claude stage: $stage" >&2
    exit 2
    ;;
esac

echo "Claude stage smoke complete in $repo_root"
