from __future__ import annotations

from typing import Any

from src.agent_orchestrator.output_guard import sanitize_llm_output


_EXPLAIN_SYSTEM_PROMPT = """You are a signal explanation assistant.
Explain why a signal was generated by the quantitative system.

Rules:
- do not output BUY or SELL
- do not create orders
- do not bypass risk checks
- return JSON only
- do not change the original signal_type
- if the signal was blocked, only explain why it was blocked
- the decision_source must be "quant_rules_and_risk_gate"
"""


class SignalExplanationAgent:
    def __init__(self, router: Any) -> None:
        self._router = router

    def explain(self, signal_draft: dict, context: dict | None = None) -> dict:
        user_prompt = (
            f"Signal: {signal_draft}\n"
            f"Context: {context}\n"
            "Generate an explanation with evidence and risk notes. "
            "Keep the original signal_type unchanged."
        )
        raw = self._router.chat_json(
            system_prompt=_EXPLAIN_SYSTEM_PROMPT,
            user_prompt=user_prompt,
            schema_name="signal_explanation",
        )
        guard_result = sanitize_llm_output(raw)
        if guard_result["blocked"]:
            return {
                "status": "blocked_by_guard",
                "signal_id": signal_draft.get("signal_id", ""),
                "original_signal_type": signal_draft.get("signal_type", ""),
                "message": "LLM output contained forbidden trade-decision content",
                "block_reasons": guard_result["block_reasons"],
                "decision_source": "quant_rules_and_risk_gate",
            }
        result = guard_result["sanitized"]
        if guard_result["warnings"]:
            result.setdefault("warnings", []).extend(guard_result["warnings"])
        if isinstance(result, dict) and result.get("status") != "unavailable":
            result["signal_id"] = signal_draft.get("signal_id", "")
            result["original_signal_type"] = signal_draft.get("signal_type", "")
            result.setdefault("decision_source", "quant_rules_and_risk_gate")
        return result
